### ISSUE TITLE
Config form broken looking for Omeka\Settings

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/FileSideload#1]
```
Zend\ServiceManager\Exception\ServiceNotFoundException: Unable to resolve service "Omeka/Settings" to a factory; are you certain you provided it during configuration? in /var/www/omekas/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:670
Stack trace:
#0 /var/www/omekas/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(746): Zend\ServiceManager\ServiceManager->getFactory('Omeka/Settings')
#1 /var/www/omekas/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(195): Zend\ServiceManager\ServiceManager->doCreate('Omeka/Settings')
#2 /var/www/omekas/modules/FileSideload/Module.php(57): Zend\ServiceManager\ServiceManager->get('Omeka/Settings')
#3 /var/www/omekas/application/src/Controller/Admin/ModuleController.php(280): FileSideload\Module->getConfigForm(Object(Zend\View\Renderer\PhpRenderer))
#4 /var/www/omekas/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Omeka\Controller\Admin\ModuleController->configureAction()
#5 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#6 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#7 /var/www/omekas/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(105): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#8 /var/www/omekas/vendor/zendframework/zend-mvc/src/DispatchListener.php(119): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#9 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#10 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /var/www/omekas/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#12 /var/www/omekas/index.php(17): Zend\Mvc\Application->run()
#13 {main}
```

**Comment by jimsafley** [comment]
Thanks for pointing this out. I've neglected this module as we've developed the core code. There's actually a bunch of stuff that needs fixing beyond this.
